USE [MSMEDS]
GO

/****** Object:  Table [dbo].[BUYER_SELLER_MAPPING]    Script Date: 10/2/2026 6:06:36 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BUYER_SELLER_MAPPING](
	[MAPPING_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BUYER_ENTITY_ID] [bigint] NOT NULL,
	[SELLER_ENTITY_ID] [bigint] NOT NULL,
	[STATUS] [varchar](20) NOT NULL,
	[CREATED_AT] [datetime2](3) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[MODIFIED_AT] [datetime2](3) NULL,
	[MODIFIED_BY] [varchar](100) NULL,
 CONSTRAINT [PK_buyer_seller_mapping] PRIMARY KEY CLUSTERED 
(
	[MAPPING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_buyer_seller] UNIQUE NONCLUSTERED 
(
	[BUYER_ENTITY_ID] ASC,
	[SELLER_ENTITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING] ADD  CONSTRAINT [DF_bsm_status]  DEFAULT ('ACTIVE') FOR [STATUS]
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING] ADD  CONSTRAINT [DF_bsm_created_at]  DEFAULT (sysutcdatetime()) FOR [CREATED_AT]
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING]  WITH CHECK ADD  CONSTRAINT [FK_bsm_buyer] FOREIGN KEY([BUYER_ENTITY_ID])
REFERENCES [dbo].[ENTITY_MASTER] ([ENTITY_ID])
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING] CHECK CONSTRAINT [FK_bsm_buyer]
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING]  WITH CHECK ADD  CONSTRAINT [FK_bsm_seller] FOREIGN KEY([SELLER_ENTITY_ID])
REFERENCES [dbo].[ENTITY_MASTER] ([ENTITY_ID])
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING] CHECK CONSTRAINT [FK_bsm_seller]
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING]  WITH CHECK ADD  CONSTRAINT [CK_bsm_status] CHECK  (([status]='INACTIVE' OR [status]='ACTIVE'))
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING] CHECK CONSTRAINT [CK_bsm_status]
GO


