USE [MSMEDS]
GO

/****** Object:  Table [dbo].[BUYER_SELLER_MAPPING_REQUEST]    Script Date: 10/2/2026 6:08:22 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BUYER_SELLER_MAPPING_REQUEST](
	[REQUEST_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BUYER_ENTITY_ID] [bigint] NOT NULL,
	[SELLER_ENTITY_ID] [bigint] NOT NULL,
	[STATUS] [varchar](30) NOT NULL,
	[CREATED_AT] [datetime2](3) NOT NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[MODIFIED_AT] [datetime2](3) NULL,
	[MODIFIED_BY] [varchar](100) NULL,
	[REJECTION_REASON] [varchar](500) NULL,
 CONSTRAINT [PK_buyer_seller_mapping_request] PRIMARY KEY CLUSTERED 
(
	[REQUEST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING_REQUEST] ADD  CONSTRAINT [DF_bsmr_status]  DEFAULT ('PENDING_APPROVAL') FOR [STATUS]
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING_REQUEST] ADD  CONSTRAINT [DF_bsmr_created_at]  DEFAULT (sysutcdatetime()) FOR [CREATED_AT]
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING_REQUEST]  WITH CHECK ADD  CONSTRAINT [FK_bsmr_buyer] FOREIGN KEY([BUYER_ENTITY_ID])
REFERENCES [dbo].[ENTITY_MASTER] ([ENTITY_ID])
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING_REQUEST] CHECK CONSTRAINT [FK_bsmr_buyer]
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING_REQUEST]  WITH CHECK ADD  CONSTRAINT [FK_bsmr_seller] FOREIGN KEY([SELLER_ENTITY_ID])
REFERENCES [dbo].[ENTITY_MASTER] ([ENTITY_ID])
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING_REQUEST] CHECK CONSTRAINT [FK_bsmr_seller]
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING_REQUEST]  WITH CHECK ADD  CONSTRAINT [CK_bsmr_status] CHECK  (([STATUS]='REJECTED' OR [STATUS]='APPROVED' OR [STATUS]='PENDING_APPROVAL'))
GO

ALTER TABLE [dbo].[BUYER_SELLER_MAPPING_REQUEST] CHECK CONSTRAINT [CK_bsmr_status]
GO


