USE [MSMEDS]
GO

/****** Object:  Table [dbo].[ENTITY_MASTER]    Script Date: 10/2/2026 6:10:37 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ENTITY_MASTER](
	[ENTITY_ID] [bigint] IDENTITY(10000000,1) NOT NULL,
	[ENTITY_TYPE] [varchar](20) NOT NULL,
	[ENTITY_NAME] [varchar](200) NOT NULL,
	[CITY] [varchar](100) NULL,
	[STATE] [varchar](100) NULL,
	[COUNTRY] [varchar](100) NULL,
	[STATUS] [varchar](20) NOT NULL,
	[CREATED_AT] [datetime2](3) NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[MODIFIED_AT] [datetime2](3) NULL,
	[MODIFIED_BY] [varchar](50) NULL,
 CONSTRAINT [PK_entity] PRIMARY KEY CLUSTERED 
(
	[ENTITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ENTITY_MASTER] ADD  CONSTRAINT [DF_entity_status]  DEFAULT ('ACTIVE') FOR [STATUS]
GO

ALTER TABLE [dbo].[ENTITY_MASTER] ADD  CONSTRAINT [DF_entity_created_at]  DEFAULT (sysutcdatetime()) FOR [CREATED_AT]
GO

ALTER TABLE [dbo].[ENTITY_MASTER]  WITH CHECK ADD  CONSTRAINT [CK_entity_status] CHECK  (([status]='INACTIVE' OR [status]='ACTIVE'))
GO

ALTER TABLE [dbo].[ENTITY_MASTER] CHECK CONSTRAINT [CK_entity_status]
GO

ALTER TABLE [dbo].[ENTITY_MASTER]  WITH CHECK ADD  CONSTRAINT [CK_entity_type] CHECK  (([entity_type]='FINANCIER' OR [entity_type]='SELLER' OR [entity_type]='BUYER'))
GO

ALTER TABLE [dbo].[ENTITY_MASTER] CHECK CONSTRAINT [CK_entity_type]
GO


